#!/usr/bin/env node

let fs = require("fs");
let path = require("path");

let lessonContent = `
# Lesson title

Perhaps include a diagram here.

{{ TOC }}

---

## Prerequisites

Put prerequisite concepts, skills, and reading material here.

---

## Learning Objectives

### Concepts

List the concepts will we learn.

* Concept 1
* Concept 2
* Concept 3

---

### Skills

List the skills we will learn.

* Skill 1
* Skill 2
* Skill 3

---

## Introduction

Introduction goes here.

* What problems are we going to solve with this material?

---

## Topic 1

### Lesson

Topic 1 material goes here.

### Exercise

Topic 1 exercise goes here.

---

## Topic 2

### Lesson

Topic 2 material goes here.

### Exercise

Topic 2 exercise goes here.

---

## Topic 3

### Lesson

Topic 3 material goes here.

### Exercise

Topic 3 exercise goes here.

---

## Summary

Summarize what we have learned.

---

## Quiz Questions

List quiz questions with answers here. For example:

<details>
  <summary><strong>Q1: What is 1 + 2?</strong></summary>
  > A: 3
</details>


<details>
  <summary><strong>Q1: What is 3 * 5?</strong></summary>
  > A: 15
</details>


<details>
  <summary><strong>Q1: What is 100 / 20?</strong></summary>
  > A: 5
</details>


## Homework

List links to sample Homework assignments.


## For Further Reading

List some resources here. For example:

* [Markdown](https://daringfireball.net/projects/markdown/)
* [Markdown Wikipedia Page](https://en.wikipedia.org/wiki/Markdown)
* [Markdown Cheat Sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
`;


let MarkDownLessonGenerator = (function() {

  // The private Implementation class
  class MarkDownLessonGeneratorImpl {
    constructor(filename, baseDir) {
      this.filename = filename;
      this.baseDir = baseDir;
    }

  }

  let impl;

  // The public class
  class MarkDownLessonGenerator {
    constructor(filename, baseDir) {
      impl = new MarkDownLessonGeneratorImpl(filename, baseDir);
    }

    get impl() {
      return impl;
    }

    process() {
      console.log(`Generating '${this.impl.filename}'...`);
      fs.writeFile(this.impl.filename, lessonContent, "utf-8", () => { console.log(`Generated ${this.impl.filename}!`); });
    }
  }

  return MarkDownLessonGenerator;
})();

let cwd = process.cwd();
new MarkDownLessonGenerator('sample-lesson-template.md', cwd).process();
